#!/bin/sh
# mkimage.sh - assemble SaviorOS boot media from one or two payloads.
#
# Produces (see docs/DESIGN.md section 13.1):
#   <out>/<name>.img      hybrid USB disk image: legacy BIOS + 64-bit UEFI + 32-bit UEFI
#   <out>/<name>.iso      CD/DVD image (BIOS El Torito + UEFI), also dd-able to USB
#   <out>/netboot/        TFTP/HTTP tree for PXE (BIOS and UEFI)
#
# The disk image is an MBR disk with GRUB's boot.img in the MBR, GRUB's
# i386-pc core image in the gap before the first partition, and a single
# FAT32 partition labeled SAVIOR that holds everything else, including the
# user-editable savior.conf.
#
# Usage:
#   mkimage.sh --out DIR --payload x86_64=VMLINUZ,INITRD [--payload i686=VMLINUZ,INITRD]
#              [--name savior] [--version V] [--formats img,iso,netboot]
#              [--conf FILE] [--grub-lib /usr/lib/grub] [--fat-mb N]
#              [--cmdline "extra kernel args"] [--timeout SECONDS]
#
# Requirements: grub-mkimage + GRUB platform modules (i386-pc, x86_64-efi,
# optionally i386-efi), mkfs.fat, mtools (mcopy, mmd), dd, and for the ISO
# xorriso, for netboot grub-mknetdir. On Debian/Ubuntu:
#   apt install grub-common grub-pc-bin grub-efi-amd64-bin grub-efi-ia32-bin \
#               dosfstools mtools xorriso
# COMMON_MODS is word-split on purpose; single-quoted GRUB variables are literal.
# shellcheck disable=SC2086,SC2016
set -eu

die() { echo "mkimage: error: $*" >&2; exit 1; }
log() { echo "mkimage: $*" >&2; }

OUT=""
NAME="savior"
VERSION="dev"
FORMATS="img,iso,netboot"
CONF=""
GRUB_LIB="${GRUB_LIB:-/usr/lib/grub}"
FAT_MB=""
EXTRA_CMDLINE=""
TIMEOUT=5
PAYLOADS=""

while [ $# -gt 0 ]; do
	case "$1" in
	--out) OUT="$2"; shift 2 ;;
	--name) NAME="$2"; shift 2 ;;
	--version) VERSION="$2"; shift 2 ;;
	--formats) FORMATS="$2"; shift 2 ;;
	--conf) CONF="$2"; shift 2 ;;
	--grub-lib) GRUB_LIB="$2"; shift 2 ;;
	--fat-mb) FAT_MB="$2"; shift 2 ;;
	--cmdline) EXTRA_CMDLINE="$2"; shift 2 ;;
	--timeout) TIMEOUT="$2"; shift 2 ;;
	--payload) PAYLOADS="$PAYLOADS $2"; shift 2 ;;
	-h|--help) sed -n '2,25p' "$0"; exit 0 ;;
	*) die "unknown argument: $1" ;;
	esac
done

[ -n "$OUT" ] || die "--out is required"
[ -n "$PAYLOADS" ] || die "at least one --payload ARCH=VMLINUZ,INITRD is required"
case "$TIMEOUT" in ''|*[!0-9]*) die "--timeout must be a number" ;; esac

need() { command -v "$1" >/dev/null 2>&1 || die "missing tool: $1 ($2)"; }
need grub-mkimage "grub-common"
need mkfs.fat "dosfstools"
need mcopy "mtools"
need mmd "mtools"
[ -d "$GRUB_LIB/i386-pc" ] || die "GRUB i386-pc modules not found in $GRUB_LIB (grub-pc-bin)"
[ -d "$GRUB_LIB/x86_64-efi" ] || die "GRUB x86_64-efi modules not found in $GRUB_LIB (grub-efi-amd64-bin)"
HAVE_IA32=no
[ -d "$GRUB_LIB/i386-efi" ] && HAVE_IA32=yes

HERE=$(cd "$(dirname "$0")" && pwd)
mkdir -p "$OUT"
OUT=$(cd "$OUT" && pwd)
WORK=$(mktemp -d "${TMPDIR:-/tmp}/savior-mkimage.XXXXXX")
trap 'rm -rf "$WORK"' EXIT INT TERM

# A build-unique marker file lets GRUB find *this* boot medium even when other
# SaviorOS disks are attached.
BUILD_ID=$(od -An -N8 -tx1 /dev/urandom | tr -d ' \n')
MARKER="/boot/savior-$BUILD_ID.id"

STAGE="$WORK/stage"
mkdir -p "$STAGE/boot/grub" "$STAGE/EFI/BOOT"
printf '%s\n' "$VERSION" >"$STAGE$MARKER"

ARCHES=""
for p in $PAYLOADS; do
	arch=${p%%=*}
	files=${p#*=}
	kernel=${files%%,*}
	initrd=${files#*,}
	case "$arch" in x86_64|i686) ;; *) die "payload arch must be x86_64 or i686, got $arch" ;; esac
	[ -f "$kernel" ] || die "kernel not found: $kernel"
	[ -f "$initrd" ] || die "initrd not found: $initrd"
	mkdir -p "$STAGE/boot/$arch"
	cp "$kernel" "$STAGE/boot/$arch/vmlinuz"
	cp "$initrd" "$STAGE/boot/$arch/initrd"
	ARCHES="$ARCHES $arch"
done
ARCHES=${ARCHES# }

# ---------------------------------------------------------------------------
# grub.cfg (shared by BIOS, UEFI, ISO and netboot)

CMDLINE="consoleblank=0 quiet loglevel=3 console=ttyS0,115200 console=tty0"
[ -n "$EXTRA_CMDLINE" ] && CMDLINE="$CMDLINE $EXTRA_CMDLINE"

write_grub_cfg() {
	cat <<EOF
# SaviorOS $VERSION boot menu (generated by os/image/mkimage.sh)
set timeout=$TIMEOUT
set default=0
set savior_cmdline="$CMDLINE"
insmod all_video
insmod gfxterm
serial --unit=0 --speed=115200
terminal_input console serial
terminal_output console serial

EOF
	# Pick the payload from what this build contains (no file tests: they
	# don't work over TFTP). With both payloads: 64-bit when the CPU has long
	# mode; 32-bit UEFI firmware (Bay Trail tablets, early Intel Macs) gets
	# the 32-bit payload because not every GRUB can hand off to a 64-bit
	# kernel there.
	case " $ARCHES " in
	*" x86_64 "*" i686 "* | *" i686 "*" x86_64 "*)
		printf '%s\n' 'set arch=x86_64' \
			'if [ "$grub_platform" = "efi" -a "$grub_cpu" = "i386" ]; then' \
			'	set arch=i686' \
			'elif ! cpuid -l; then' \
			'	set arch=i686' \
			'fi'
		;;
	*" x86_64 "*)
		printf '%s\n' 'set arch=x86_64' \
			'if ! cpuid -l; then' \
			'	echo "This CPU is 32-bit only, but this SaviorOS build has only the 64-bit payload."' \
			'	echo "Use the i686 or universal image. Trying anyway in 10 seconds..."' \
			'	sleep 10' \
			'fi'
		;;
	*) echo 'set arch=i686' ;;
	esac
	cat <<EOF

menuentry "SaviorOS \$arch" {
	linux /boot/\$arch/vmlinuz \$savior_cmdline
	initrd /boot/\$arch/initrd
}
menuentry "SaviorOS \$arch - safe graphics (nomodeset)" {
	linux /boot/\$arch/vmlinuz \$savior_cmdline nomodeset
	initrd /boot/\$arch/initrd
}
menuentry "SaviorOS \$arch - display only" {
	linux /boot/\$arch/vmlinuz \$savior_cmdline savior.roles=display
	initrd /boot/\$arch/initrd
}
menuentry "SaviorOS \$arch - rescue shell on tty2, verbose boot" {
	linux /boot/\$arch/vmlinuz consoleblank=0 loglevel=7 console=ttyS0,115200 console=tty0 savior.console_shell=yes
	initrd /boot/\$arch/initrd
}
EOF
	case " $ARCHES " in *" i686 "*)
		cat <<'EOF'
menuentry "SaviorOS i686 (force 32-bit)" {
	linux /boot/i686/vmlinuz $savior_cmdline
	initrd /boot/i686/initrd
}
EOF
	;; esac
	cat <<'EOF'
menuentry "Reboot" { reboot }
menuentry "Power off" { halt }
EOF
}
write_grub_cfg >"$STAGE/boot/grub/grub.cfg"
if command -v grub-script-check >/dev/null 2>&1; then
	grub-script-check "$STAGE/boot/grub/grub.cfg" || die "generated grub.cfg failed grub-script-check"
fi

# Early config baked into the core images: find this medium, load the menu.
cat >"$WORK/early.cfg" <<EOF
search --no-floppy --file --set=root $MARKER
set prefix=(\$root)/boot/grub
configfile (\$root)/boot/grub/grub.cfg
EOF

# ---------------------------------------------------------------------------
# savior.conf and README on the stick

if [ -n "$CONF" ]; then
	[ -f "$CONF" ] || die "config not found: $CONF"
	cp "$CONF" "$STAGE/savior.conf"
elif [ -f "$HERE/savior.conf.template" ]; then
	cp "$HERE/savior.conf.template" "$STAGE/savior.conf"
else
	printf '# SaviorOS configuration. See README.txt.\n#swarm_key =\n' >"$STAGE/savior.conf"
fi
if [ -f "$HERE/README.txt" ]; then
	sed "s/@VERSION@/$VERSION/g" "$HERE/README.txt" >"$STAGE/README.txt"
fi
# Windows-friendly line endings for the files people edit on any computer.
for f in "$STAGE/savior.conf" "$STAGE/README.txt"; do
	[ -f "$f" ] && sed -i 's/\r*$/\r/' "$f"
done

# ---------------------------------------------------------------------------
# GRUB images

COMMON_MODS="part_msdos part_gpt fat iso9660 normal linux echo test configfile cpuid search search_fs_file search_label ls cat sleep reboot halt minicmd serial terminal gfxterm font all_video"
log "building GRUB images"
grub-mkimage -O i386-pc -d "$GRUB_LIB/i386-pc" -c "$WORK/early.cfg" -p /boot/grub \
	-o "$WORK/core.img" biosdisk $COMMON_MODS
if [ "$(wc -c <"$WORK/core.img")" -gt $((2047 * 512)) ]; then
	die "i386-pc core image too large for the MBR gap"
fi
grub-mkimage -O x86_64-efi -d "$GRUB_LIB/x86_64-efi" -c "$WORK/early.cfg" -p /boot/grub \
	-o "$STAGE/EFI/BOOT/BOOTX64.EFI" $COMMON_MODS efi_gop efi_uga
if [ "$HAVE_IA32" = yes ]; then
	grub-mkimage -O i386-efi -d "$GRUB_LIB/i386-efi" -c "$WORK/early.cfg" -p /boot/grub \
		-o "$STAGE/EFI/BOOT/BOOTIA32.EFI" $COMMON_MODS efi_gop efi_uga
else
	log "warning: no i386-efi GRUB modules; image won't boot on 32-bit UEFI"
fi

# ---------------------------------------------------------------------------
# Disk image

le32() {
	# Print a 32-bit little-endian integer as raw bytes.
	n=$1
	for _ in 1 2 3 4; do
		# shellcheck disable=SC2059 # the format string is the octal escape
		printf "\\$(printf '%03o' $((n & 255)))"
		n=$((n >> 8))
	done
}

build_img() {
	img="$OUT/$NAME.img"
	content_kb=$(du -sk "$STAGE" | cut -f1)
	if [ -z "$FAT_MB" ]; then
		# payload + 25% + 48 MiB free for hive data / logs, rounded up to 8 MiB,
		# at least 64 MiB so FAT32 has enough clusters.
		FAT_MB=$(( (content_kb * 5 / 4 / 1024 + 48 + 7) / 8 * 8 ))
		[ "$FAT_MB" -lt 64 ] && FAT_MB=64
	fi
	part_sectors=$((FAT_MB * 2048))
	start=2048
	log "building $img (FAT32 partition ${FAT_MB} MiB)"

	part="$WORK/part.img"
	rm -f "$part"
	dd if=/dev/zero of="$part" bs=1M count=0 seek="$FAT_MB" 2>/dev/null
	mkfs.fat -F 32 -n SAVIOR -i "$(echo "$BUILD_ID" | cut -c1-8)" "$part" >/dev/null
	MTOOLS_SKIP_CHECK=1 mcopy -s -Q -i "$part" "$STAGE"/* ::/

	rm -f "$img"
	dd if=/dev/zero of="$img" bs=512 count=0 seek=$((start + part_sectors)) 2>/dev/null
	# MBR: GRUB boot code (first 440 bytes of boot.img), disk signature,
	# one bootable FAT32-LBA partition, 0x55AA.
	dd if="$GRUB_LIB/i386-pc/boot.img" of="$img" bs=440 count=1 conv=notrunc 2>/dev/null
	le32 $((0x$(echo "$BUILD_ID" | cut -c9-16))) | dd of="$img" bs=1 seek=440 conv=notrunc 2>/dev/null
	{
		printf '\200'                # status: bootable
		printf '\040\041\000'        # CHS start (LBA 2048 in 64/32 geometry)
		printf '\014'                # type 0x0C: FAT32 LBA
		printf '\376\377\377'        # CHS end: beyond 8 GiB marker
		le32 "$start"
		le32 "$part_sectors"
	} | dd of="$img" bs=1 seek=446 conv=notrunc 2>/dev/null
	printf '\125\252' | dd of="$img" bs=1 seek=510 conv=notrunc 2>/dev/null
	# GRUB core image right after the MBR (sector 1).
	dd if="$WORK/core.img" of="$img" bs=512 seek=1 conv=notrunc 2>/dev/null
	# The FAT32 partition.
	dd if="$part" of="$img" bs=1M seek=1 conv=notrunc 2>/dev/null
	rm -f "$part"
	log "wrote $img ($(du -h "$img" | cut -f1))"
}

build_iso() {
	need xorriso "xorriso"
	iso="$OUT/$NAME.iso"
	log "building $iso"
	isostage="$WORK/iso"
	mkdir -p "$isostage/boot/grub/i386-pc"
	cp -R "$STAGE/boot/." "$isostage/boot/"
	cp -R "$STAGE/EFI" "$isostage/"
	for f in savior.conf README.txt; do
		[ -f "$STAGE/$f" ] && cp "$STAGE/$f" "$isostage/"
	done
	# BIOS: El Torito no-emulation image (cdboot.img + core image).
	grub-mkimage -O i386-pc-eltorito -d "$GRUB_LIB/i386-pc" -c "$WORK/early.cfg" -p /boot/grub \
		-o "$isostage/boot/grub/i386-pc/eltorito.img" biosdisk $COMMON_MODS
	# UEFI: a small FAT image holding the same EFI loaders as the stick.
	efi_kb=$(( $(du -sk "$STAGE/EFI" | cut -f1) + 256 ))
	mkfs.fat -C "$isostage/efi.img" "$efi_kb" >/dev/null
	MTOOLS_SKIP_CHECK=1 mcopy -s -Q -i "$isostage/efi.img" "$STAGE/EFI" ::/
	# Same layout grub-mkrescue produces: hybrid MBR for USB, GPT EFI partition.
	xorriso -as mkisofs -quiet -o "$iso" -V SAVIOR -r -J \
		-b boot/grub/i386-pc/eltorito.img -no-emul-boot -boot-load-size 4 \
		-boot-info-table --grub2-boot-info \
		--grub2-mbr "$GRUB_LIB/i386-pc/boot_hybrid.img" \
		--efi-boot efi.img -efi-boot-part --efi-boot-image \
		--protective-msdos-label \
		"$isostage" >"$WORK/xorriso.log" 2>&1 || { cat "$WORK/xorriso.log" >&2; die "xorriso failed"; }
	log "wrote $iso ($(du -h "$iso" | cut -f1))"
}

build_netboot() {
	need grub-mknetdir "grub-common"
	nb="$OUT/netboot"
	log "building $nb/"
	rm -rf "$nb"
	mkdir -p "$nb"
	for plat in i386-pc x86_64-efi i386-efi; do
		[ -d "$GRUB_LIB/$plat" ] || continue
		grub-mknetdir --net-directory="$nb" --subdir=boot/grub -d "$GRUB_LIB/$plat" >/dev/null 2>&1 ||
			die "grub-mknetdir failed for $plat"
	done
	cp -R "$STAGE/boot/"* "$nb/boot/"
	rm -f "$nb$MARKER"
	# Over the network the root is the TFTP server; paths stay the same.
	cp "$STAGE/boot/grub/grub.cfg" "$nb/boot/grub/grub.cfg"
	cat >"$nb/README.txt" <<EOF
SaviorOS $VERSION netboot tree.
Serve this directory over TFTP. PXE boot files:
  BIOS:        boot/grub/i386-pc/core.0
  UEFI 64-bit: boot/grub/x86_64-efi/core.efi
  UEFI 32-bit: boot/grub/i386-efi/core.efi
Netbooted nodes have no stick to read savior.conf from: put savior.<key>=<value>
settings (at least savior.swarm_key) into savior_cmdline in boot/grub/grub.cfg.
The hive does this automatically when netboot=yes.
EOF
}

case ",$FORMATS," in *,img,*) build_img ;; esac
case ",$FORMATS," in *,iso,*) build_iso ;; esac
case ",$FORMATS," in *,netboot,*) build_netboot ;; esac
log "done (payloads: $ARCHES)"
